pgadm: refactor

diff --git a/pgadm b/pgadm
--- a/pgadm
+++ b/pgadm
@@ -5,25 +5,25 @@ set -o pipefail
 
 readonly SELF="$(basename ${BASH_SOURCE[0]})"
 readonly SELF_DIR="$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null 2>&1 && pwd)"
-readonly OS=$(uname)
-readonly VERSION=1.0.4
-
-readonly OPT_BASE_NAME=${SELF}
+readonly OS="$(uname)"
+readonly VERSION="1.0.7"
 
 OPT_HELP=
 OPT_DEBUG=
 OPT_VERBOSE=
+OPT_VERSION=
 
-OPT_CONFIG=
+OPT_CONFIG=/var/miki/config.yml
 OPT_IMPORT=
 OPT_EXPORT=
 OPT_FILE=
+OPT_EXCLUDE_TABLE=users
 
-DATABASE_HOST=
-DATABASE_NAME=
-DATABASE_PORT=
-DATABASE_USER=
-DATABASE_PASSWORD=
+VAL_DATABASE_HOST=
+VAL_DATABASE_NAME=
+VAL_DATABASE_PORT=
+VAL_DATABASE_USER=
+VAL_DATABASE_PASSWORD=
 
 OPT_DATABASE_HOST=
 OPT_DATABASE_PORT=
@@ -33,9 +33,9 @@ OPT_DATABASE_PASSWORD=
 
 function error () {
   if [[ "${OS}" == "Darwin" ]]; then
-    echo "error: ${@}" >&2
+    echo "ERROR: ${@}" >&2
   else
-    echo -e "\e[0;31m\e[1merror: \e[0;0m${@}" >&2
+    echo -e "\e[0;31m\e[1mERROR: \e[0;0m${@}" >&2
   fi
 
   exit 1
@@ -43,24 +43,24 @@ function error () {
 
 function warn () {
   if [[ "${OS}" == "Darwin" ]]; then
-    echo "warning: ${@}" >&2
+    echo "WARNING: ${@}" >&2
   else
-    echo -e "\e[0;33mwarning: \e[0;0m${@}" >&2
+    echo -e "\e[0;33mWARNING: \e[0;0m${@}" >&2
   fi
 }
 
 function debug () {
   if [[ -n "${OPT_DEBUG}" ]]; then
-    echo '**'
-    echo \${@}: ${@}
-    echo \$OPT_DEBUG: "${OPT_DEBUG}"
+    echo -n "** "
+    echo "\${PWD}: ${PWD}"
+    echo "\${@}: ${@}"
   fi
 }
 
 function parse_arguments () {
   debug ${FUNCNAME[0]} "$@"
 
-  local opts=$(getopt -n "${SELF}" --options C:IEH:p:N:U:P --longoptions help,debug,verbose,config:,import,export,database-host:,database-port:,database-name:,database-user:,database-password: -- "$@")
+  local opts=$(getopt -n "${SELF}" --options C:IEf:e:H:p:N:U:P --longoptions help,debug,verbose,version,config:,import,export,file:,exclude-table:,database-host:,database-port:,database-name:,database-user:,database-password: -- "$@")
 
   if [[ $? != 0 ]]; then
     error "Failed to parse arguments. Exiting."
@@ -73,9 +73,12 @@ function parse_arguments () {
       (--help) OPT_HELP=true; shift ;;
       (--debug) OPT_DEBUG=true; shift ;;
       (--verbose) OPT_VERBOSE=true; shift ;;
+      (--version) OPT_VERSION=true; shift ;;
       (-C|--config) OPT_CONFIG=$2; shift 2 ;;
       (-I|--import) OPT_IMPORT=true; shift ;;
       (-E|--export) OPT_EXPORT=true; shift ;;
+      (-f|--file) OPT_FILE=$2; shift 2 ;;
+      (-e|--exclude-table) OPT_EXCLUDE_TABLE=$2; shift 2 ;;
       (-H|--database-host) OPT_DATABASE_HOST=$2; shift 2 ;;
       (-p|--database-port) OPT_DATABASE_PORT=$2; shift 2 ;;
       (-N|--database-name) OPT_DATABASE_NAME=$2; shift 2 ;;
@@ -85,8 +88,6 @@ function parse_arguments () {
       (*) break ;;
     esac
   done
-
-  OPT_FILE="${@: -1}"
 }
 
 function process_arguments () {
@@ -94,6 +95,8 @@ function process_arguments () {
 
   if [[ -n "${OPT_HELP}" || "${#}" -lt 1 ]]; then
     display_usage
+  elif [[ -n "${OPT_VERSION}" ]]; then
+    display_version
   elif [[ -z "${OPT_CONFIG}" ]]; then
     display_usage
   else
@@ -108,17 +111,27 @@ function display_usage () {
 ${SELF} v${VERSION} [OPTIONS]...
 
 OPTIONS:
-      --help              Show this help
-      --debug             Enable debugging mode
-      --verbose           Enable verbose output
-  -C, --config            Set config source
-  -I, --import            Perform database import
-  -E, --export            Perform database export
-  -H, --database-host     Set the database host
-  -p, --database-port     Set the database port
-  -N, --database-name     Set the database name
-  -U, --database-user     Set the database user
-  -P, --database-password Set the database password
+      --help               Show this help
+      --debug              Enable debugging mode
+      --verbose            Enable verbose output
+      --version            Display program version info
+  -C, --config             Set config source
+  -I, --import             Perform database import
+  -E, --export             Perform database export
+  -H, --database-host      Set the database host
+  -p, --database-port      Set the database port
+  -N, --database-name      Set the database name
+  -U, --database-user      Set the database user
+  -P, --database-password  Set the database password
+EOF
+  exit 0
+}
+
+function display_version () {
+  debug ${FUNCNAME[0]} "$@"
+
+  cat << EOF
+${SELF} v${VERSION}
 EOF
   exit 0
 }
@@ -134,11 +147,11 @@ function get_value () {
 function set_parameters () {
   debug ${FUNCNAME[0]} "$@"
 
-  DATABASE_HOST=$(get_value host)
-  DATABASE_PORT=$(get_value port)
-  DATABASE_NAME=$(get_value db)
-  DATABASE_USER=$(get_value user)
-  DATABASE_PASSWORD=$(get_value pass)
+  VAL_DATABASE_HOST=$(get_value host)
+  VAL_DATABASE_PORT=$(get_value port)
+  VAL_DATABASE_NAME=$(get_value db)
+  VAL_DATABASE_USER=$(get_value user)
+  VAL_DATABASE_PASSWORD=$(get_value pass)
 }
 
 function export_database () {
@@ -146,11 +159,11 @@ function export_database () {
 
   PGPASSWORD=${OPT_DATABASE_PASSWORD:-$DATABASE_PASSWORD} \
             pg_dump \
-            -h "${OPT_DATABASE_HOST:-$DATABASE_HOST}" \
-            -p "${OPT_DATABASE_PORT:-$DATABASE_PORT}" \
-            -U "${OPT_DATABASE_USER:-$DATABASE_USER}" \
+            -h "${OPT_DATABASE_HOST:-$VAL_DATABASE_HOST}" \
+            -p "${OPT_DATABASE_PORT:-$VAL_DATABASE_PORT}" \
+            -U "${OPT_DATABASE_USER:-$VAL_DATABASE_USER}" \
             -Fc \
-            "${OPT_DATABASE_NAME:-$DATABASE_NAME}" \
+            "${OPT_DATABASE_NAME:-$VAL_DATABASE_NAME}" \
             -f "${OPT_FILE}"
 }
 
@@ -160,21 +173,21 @@ function import_database () {
   PGPASSWORD=${OPT_DATABASE_PASSWORD:-$DATABASE_PASSWORD} \
             pg_restore \
             -c \
-            -h "${OPT_DATABASE_HOST:-$DATABASE_HOST}" \
-            -p "${OPT_DATABASE_PORT:-$DATABASE_PORT}" \
-            -d "${OPT_DATABASE_NAME:-$DATABASE_NAME}" \
-            -U "${OPT_DATABASE_USER:-$DATABASE_USER}" \
+            -h "${OPT_DATABASE_HOST:-$VAL_DATABASE_HOST}" \
+            -p "${OPT_DATABASE_PORT:-$VAL_DATABASE_PORT}" \
+            -d "${OPT_DATABASE_NAME:-$VAL_DATABASE_NAME}" \
+            -U "${OPT_DATABASE_USER:-$VAL_DATABASE_USER}" \
             "${OPT_FILE}"
 }
 
 function credentials_ok () {
   debug ${FUNCNAME[0]} "$@"
 
-  if [[ -n "${OPT_DATABASE_HOST:-$DATABASE_HOST}" && \
-          -n "${OPT_DATABASE_PORT:-$DATABASE_PORT}" && \
-          -n "${OPT_DATABASE_NAME:-$DATABASE_NAME}" && \
-          -n "${OPT_DATABASE_USER:-$DATABASE_USER}" && \
-          -n "${OPT_DATABASE_PASSWORD:-$DATABASE_PASSWORD}" ]]; then
+  if [[ -n "${OPT_DATABASE_HOST:-$VAL_DATABASE_HOST}" && \
+          -n "${OPT_DATABASE_PORT:-$VAL_DATABASE_PORT}" && \
+          -n "${OPT_DATABASE_NAME:-$VAL_DATABASE_NAME}" && \
+          -n "${OPT_DATABASE_USER:-$VAL_DATABASE_USER}" && \
+          -n "${OPT_DATABASE_PASSWORD:-$VAL_DATABASE_PASSWORD}" ]]; then
     return 0
   else
     return 1
